name: Docker CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker containers
        # 'docker compose' (boşluqla) yeni standartdır, 'docker-compose' yerinə bunu istifadə et
        run: docker compose build